name: Xcode - Build and Analyze

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild build -workspace Easydict.xcworkspace -scheme Easydict -configuration Release -derivedDataPath Build CODE_SIGN_IDENTITY="-" CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=""
      - name: Package app
        run: |
          app_path=$(find Build/Build/Products -name "*.app" -type d | head -n 1)
          echo "Found app: $app_path"
          ditto -c -k --keepParent "$app_path" Easydict.app.zip
      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: Easydict-app
          path: Easydict.app.zip
          if-no-files-found: error
